language: python
python:
  - "3.6"
before_install:
  - echo "travis before_install"
intall:
  - echo "travis install"
  - pip install -r requirements.txt

before_script:
  - cd scripts/
  - bash qalab-core.sh -h

script:
  - cd scripts/
  - bash qacode.sh test-loggers
  - bash qacode.sh test-configs
