branches:
  only:
  - master
  - devel
env:
  global:
  - secure: e4j7f4oVrkMJxgxqNqHFDKyatA3f6jbMcCE1ZiUpNiase9NsnlUWunzMF5XVZWQKaN+c+XE1TRKne/nM3Xageovx4KcmVMD6AmUFWkXfQLMg4VkpQ8UdmLRpoZniOPpjqC8w7sL6PRwIwuwbu412D5eQOWDyorn+xo1i5vpb28+S9FiDLICx6oRjtAY2YK5Ab1+rHC9EjD2+agluSntqhKlynxTEmNWn3VIuQgt08TbGyTsWSA/yb9g4xLTQ0lcp5zF1l7MWgCCvugmxl+kneUvExnxsrbpUgLNzCmxI7uad+M7s5SiBcmW43LC7Fo3gSxu1eHTTR4F+2RML/hE8AodAqVav/pfumA/q97Be5uvZxluV9ofRq1Gx1yongKb78tDmKnMtR56PUPx527dH59+1/gKFFtiAgfjDJ/qIzrDkGVPm0WnsLGrnOEnXvE0pxe2rO9I+BCdheGQ4xEWCImkyIK5c+ET+plCZXavdNGIvyFpAwPRg5nhZurf2kXcXiMqa5eLZpo+QFhaDOya85Z9lKI0d6Eie01ETM0WOAD5QhTKW4JrKxI8/PB2Lhcsv/5+wX1zu5wt1X8lgz5DZYbseHykxk72/oDdgizjKUkIRIeiE4z+wm6ujMQoi3Hqd+85d9gcealO/mOgLd45HrIEXCGaULsh9pxvuWtFMQDes
addons:
  sonarqube:
    branches:
      - master
      - devel

language: python
python:
- '2.7'
- '3.2'
- '3.3'
- '3.4'
- '3.5'
- '3.6'
before_install:
- pip freeze
install:
- python setup.py install
before_script:
- cp qacode/configs/settings.example.ini qacode/configs/settings.ini
script:
- nosetests tests/unitaries/TestConfig.py --tc-file="qacode/configs/settings.ini"
- nosetests tests/unitaries/TestLoggerManager.py --tc-file="qacode/configs/settings.ini"
- nosetests tests/unitaries/TestTestInfoBase.py --tc-file="qacode/configs/settings.ini"
- echo "TESTS UNITARIES SUCCESS"
- nosetests tests/functionals/TestBotBase.py:TestBotBase.test_006_bot_remote_chrome --tc-file="qacode/configs/settings.ini"
- nosetests tests/functionals/TestBotBase.py:TestBotBase.test_008_bot_remote_phantomjs --tc-file="qacode/configs/settings.ini"
- nosetests tests/functionals/TestNavBase.py --tc-file="qacode/configs/settings.ini"
- nosetests tests/functionals/TestPageBase.py --tc-file="qacode/configs/settings.ini"
- echo "TESTS FUNCTIONALS SUCCESS"

after_script:
- sonar-scanner -X -Dsonar.login=${SONAR_GITHUB_TOKEN} -Dsonar.host.url=http://qalab.tk:82
