env:
  global:
  - secure: ondIx9iLPeA4EkO6d0bzuBf8/9hCCVIzINd0tptThPSlXQTinLQoyRVGBCHYny5NkXPcidwSocRP0LPDYt4UZdY2/mfsDDO+KQR7BIiImHpVdSH+AOVPPUwMC5z9xn9ibR1rpa3PkMbmtD/EJ4BGqCyTfOSYwvBd+qHL0yzNYzyUW8O93R53l2KFGZx0BowKbITUz4DGG+lQRyrSP8gmq9WjZg1siBToDIE+ivWg5tPoOHmOxw1h71S5UeZIPJYn/nXyDXXWXuluZi9QUiPEAepW1fDb8aGWU3hVwzRNKtMVJ89Ef/VpiukYgPCR7bZxN+G8gc0TLEEEyhJnIz39JeCNE1z0mHyR9v4LJxJYC9wuPFIXvOUUZGRyTbDs1LWejuxURI52GOtL3HcmcpReMMSK0M8M1/YiyydpSvD7C+D0SMSG0CSiOv6iE48gqbpEWhTTLphpEmKIJiZgzS5mrfIJjaWuDbf0pj4ZIt+YqkNmL3Z8Bi4/GTLePw0liyUekWvk59bsNXLKhVzMRrqp9+LVq8gaGDD/a2dsFHE3iAHN2VXXsqLcEn6zSZwkLUAMg6Q4WQJHtouSlnjbapITkiQZIgdoQ10aLE1q89xm7FYIgBv0QwpByG3k9zxFD3OKfjcwbyXdy8e+XlGUKTy1ypGp4Ubrjzk+9ZIAsmYeWXM=
  - secure: e4j7f4oVrkMJxgxqNqHFDKyatA3f6jbMcCE1ZiUpNiase9NsnlUWunzMF5XVZWQKaN+c+XE1TRKne/nM3Xageovx4KcmVMD6AmUFWkXfQLMg4VkpQ8UdmLRpoZniOPpjqC8w7sL6PRwIwuwbu412D5eQOWDyorn+xo1i5vpb28+S9FiDLICx6oRjtAY2YK5Ab1+rHC9EjD2+agluSntqhKlynxTEmNWn3VIuQgt08TbGyTsWSA/yb9g4xLTQ0lcp5zF1l7MWgCCvugmxl+kneUvExnxsrbpUgLNzCmxI7uad+M7s5SiBcmW43LC7Fo3gSxu1eHTTR4F+2RML/hE8AodAqVav/pfumA/q97Be5uvZxluV9ofRq1Gx1yongKb78tDmKnMtR56PUPx527dH59+1/gKFFtiAgfjDJ/qIzrDkGVPm0WnsLGrnOEnXvE0pxe2rO9I+BCdheGQ4xEWCImkyIK5c+ET+plCZXavdNGIvyFpAwPRg5nhZurf2kXcXiMqa5eLZpo+QFhaDOya85Z9lKI0d6Eie01ETM0WOAD5QhTKW4JrKxI8/PB2Lhcsv/5+wX1zu5wt1X8lgz5DZYbseHykxk72/oDdgizjKUkIRIeiE4z+wm6ujMQoi3Hqd+85d9gcealO/mOgLd45HrIEXCGaULsh9pxvuWtFMQDA=

addons:
  sonarqube:
    token:
      secure: JXG66I32t4JafFo1G6KCJdMP9v6+OKkpu22O3+jEqfMmIIUzasDwoKtWnNuJaZCw92mOxfYmjTQ3Z2gnFY/bP//g5aYSwvhl+d15f+Km/2m1Kf3xD4lED44Ygesk9iJlndyQPG433EPSSCE9tvzFgxLsSAyzzz/IjeYm2SsWt/CZp0XYgAyEeGSfpnOLuGc2jsAX+XxcnREncPG19jgYxb+kLafAQ/PJuINVjtBHUONpFWY5XsPQLApinAtzTnM/HXqFhae/zyPbw2GNA9S/OKm7ALeWoaCZzPj8KCVkeoNSA6m0w+0uib3J08RjD2YsLYk/CiyOU6CxVXsq8fQL2lR9mUqqOzjHYzfeN6NbYM0mewOnv8ZgGyeLC78Va7jFQLW8biztEvTuh+sGX2frbZkscpfkUmwomGes8ZwkLdNlEj2trZHDNwSMV/QvSSV0ueAUBf+1oqto89bMsx8rO1QfdAtytqmeL7qIR29OwlRqylrcyMBRCEU2enk7zh0DnshIVvnlug6bGWeIk7F33kD3NU5ufz0REc7IQmHPEhcdLQqJZ3pFsXHbNDwinC1iBmqd0mPYllmrjFWF5eNcLOF5vCnjRk0PwuZoHmYK+KqIeLuktXuhEggBqbVa0yxX4YOtwwXhmoUvSzwucp2g5d8KX4r1awiDaD6c7DnDj1w=
branches:
  only:
  - master
  - devel

language: python
python:
- '2.7'
- '3.2'
- '3.3'
- '3.4'
- '3.5'
- '3.6'
before_install:
- pip freeze
install:
- python setup.py install
before_script:
- cp qacode/configs/settings.example.ini qacode/configs/settings.ini
script:
- nosetests tests/unitaries/TestConfig.py --tc-file="qacode/configs/settings.ini"
- nosetests tests/unitaries/TestLoggerManager.py --tc-file="qacode/configs/settings.ini"
- echo "FINISHED AUTOMATED BUILD"
