branches:
  only:
  - master
language: python
python:
  - "2.7"
  - "3.2"
  - "3.3"
  - "3.4"
  - "3.5"
  - "3.6"
before_install:
  - pip freeze
intall:
  - python setup.py install

before_script:
  - nosetests tests/unitaries/TestConfig.py --tc-file="qacode/configs/settings.example.ini"
  - nosetests tests/unitaries/TestLoggerManager.py --tc-file="qacode/configs/settings.example.ini"

script:
  - echo "FINISHED AUTOMATED BUILD"
