language: python
python:
  - "2.7"
  - "3.2"
  - "3.3"
  - "3.4"
  - "3.5"
  - "3.6"
before_install:
  - echo "travis before_install"
intall:
  - echo "travis install"
  - pip install -r requirements.txt

before_script:
  - bash qacode/scripts/qacode.sh -h

script:
  - bash qacode/scripts/qacode.sh test-loggers
  - bash qacode/scripts/qacode.sh test-configs
