build: off
branches:
  only:
    - master
    - devel
environment:
  matrix:
    - PYTHON: "C:\\Python27"
    - PYTHON: "C:\\Python33"
    - PYTHON: "C:\\Python34"
    - PYTHON: "C:\\Python35"
    - PYTHON: "C:\\Python27-x64"
    - PYTHON: "C:\\Python33-x64"
      DISTUTILS_USE_SDK: "1"
    - PYTHON: "C:\\Python34-x64"
      DISTUTILS_USE_SDK: "1"
    - PYTHON: "C:\\Python35-x64"

install:
- "%PYTHON%\\python.exe -m pip install wheel"
- "%PYTHON%\\python.exe setup.py install"

before_test:
- "%PYTHON%\\Scripts\\nosetests tests\\unitaries\\
- "echo TESTS UNITARIES SUCCESS"

test_script:
- "%PYTHON%\\Scripts\\nosetests tests\\functionals\\
- echo "TESTS FUNCTIONALS SUCCESS"
