build: off
branches:
  only:
    - master
environment:
  matrix:
    - PYTHON: "C:\\Python27"
    - PYTHON: "C:\\Python33"
    - PYTHON: "C:\\Python34"
    - PYTHON: "C:\\Python35"
    - PYTHON: "C:\\Python27-x64"
    - PYTHON: "C:\\Python33-x64"
      DISTUTILS_USE_SDK: "1"
    - PYTHON: "C:\\Python34-x64"
      DISTUTILS_USE_SDK: "1"
    - PYTHON: "C:\\Python35-x64"

install:
  - "%PYTHON%\\python.exe setup.py install"

before_test:
  - "xcopy \"qacode\\configs\\settings.example.ini\" \"qacode\\configs\\settings.ini*\""

test_script:
  - "nosetests tests\\unitaries\\TestConfig.py --tc-file=qacode\\configs\\settings.ini"
