build: off
branches:
  only:
    - master
    - devel
environment:
  matrix:
    - TOXENV: py27
    - TOXENV: py33
    - TOXENV: py34
    - TOXENV: py35
    - TOXENV: py36

install:
- "%PYTHON%\\python.exe -m pip install wheel"
- "%PYTHON%\\python.exe setup.py install"
- "%PYTHON%\\python.exe -m pip install --pre -U tox"

test_script:
- "%PYTHON%\\python.exe setup.py develop"
- "%PYTHON%\\scripts\\tox"
