build: off
branches:
  only:
    - master
    - devel
environment:
  matrix:
    - TOXENV: py27
    - TOXENV: py33
    - TOXENV: py34
    - TOXENV: py35
    - TOXENV: py36

install:
- "python -c \"import os; open('python{0}.{1}.bat'.format(*os.environ['TOXENV'][2:]), 'w').write('@{0}\\\\python \\x25*\\n'.format(os.environ['PYTHON']))\""
- "%PYTHON% -m pip install wheel"
- "%PYTHON% -m pip install --pre -U tox"
- "%PYTHON% setup.py install"

test_script:
- "%PYTHON%\\scripts\\tox"

artifacts:
- path: dist\*"
